name: Import Issues (Advanced)
on:
  pull_request:
    paths:
      - 'data/issues.json'

jobs:
  dry-run-import:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Dry Run Issue Import
        uses: dsanchezcr/issue-importer-action@v1.0.0
        with:
          file-path: 'data/issues.json'
          file-format: json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: true

  import-issues:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Import Issues
        uses: dsanchezcr/issue-importer-action@v1
        with:
          file-path: 'data/issues.json'
          file-format: json
          github-token: ${{ secrets.GITHUB_TOKEN }}
